const $=id=>document.getElementById(id), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let frames=[{id:1,name:'Veľký portrét',w:50,h:70,hooks:[{x:25,y:8}]},{id:2,name:'Malý príbeh',w:30,h:40,hooks:[{x:15,y:5}]},{id:3,name:'Na šírku',w:50,h:40,hooks:[{x:25,y:6}]}],nextId=4,editing=null,mode='art',result;
const fmt=n=>new Intl.NumberFormat('sk-SK',{maximumFractionDigits:1}).format(n), colors=['#a7b4a0','#c5b3a1','#8eaaa1','#b4bfae','#b8a99c'], pluralWord=(n,one,few,many)=>n===1?one:n>=2&&n<=4?few:many;
function config(){return Object.fromEntries(['wallW','wallH','gap','center','columns','align','layoutType'].map(k=>[k,['columns','align','layoutType'].includes(k)?$(k).value:Number($(k).value)]))}
let selectedId=null,dragging=null,undoStack=[],alignGuides=null;
let draftArt=null,artRequest=0;
let lastGridStep=5;
function gridStep(){const n=Number($('gridStep').value.trim().replace(',', '.'));if(Number.isFinite(n)&&n>0)lastGridStep=n;return lastGridStep}
function render(){const cfg=config();$('count').textContent=frames.length; $('sampleHint').hidden=!isSample||!frames.length; $('frames').innerHTML=frames.map((f,i)=>`<button class="frame-row" data-edit="${f.id}"><span class="mini">${i+1}</span><span><strong>${esc(f.name)}</strong><small>${fmt(f.w)} × ${fmt(f.h)} cm · ${f.hooks.length===1?'1 uško':'2 ušká'}</small></span><span class="edit-icon">↗</span></button>`).join('');$('add').disabled=frames.length>=24;
if(['wallW','wallH','gap','center'].some(k=>!$(k).checkValidity()||!$(k).value)){ $('warning').textContent='Doplň platné rozmery steny a rozloženia.';result=null;renderDrillPlan();$('coordinates').innerHTML='';$('canvas').innerHTML='Doplň rozmery naľavo.';$('print').disabled=true;return }
result=calculateLayout(frames,cfg); if(result.overlap){$('moveStatus').textContent='Rámy sa prekrývajú. Posuň ich od seba.';}$('warning').textContent=result.valid?'':result.overlap?'Rámy sa prekrývajú. Plán bude dostupný po ich oddelení.':result.gapViolation?`Medzera medzi rámami je menšia než ${fmt(cfg.gap)} cm. Posuň rámy ďalej od seba alebo zníž medzeru.`:(cfg.layoutType==='manual'?'Zostava presahuje stenu. Presuň rámy tak, aby sa zmestili na stenu, alebo stenu zväčši. Plán vŕtania sa zobrazí, keď sa všetky rámy zmestia.':'Zostava presahuje stenu. Zmeň počet stĺpcov, medzery alebo výšku stredu. Plán vŕtania sa zobrazí, keď sa všetky rámy zmestia.');$('print').disabled=!result.valid||!frames.length;let holeCount=frames.reduce((s,f)=>s+f.hooks.length,0);$('holes').textContent=fmt(holeCount)+' '+pluralWord(holeCount,'bod','body','bodov');$('layoutSummary').textContent=frames.length?`${cfg.layoutType==='manual'?'Vlastné polohy':cfg.layoutType==='compact'?'Kompaktne · '+result.columns+' '+pluralWord(result.columns,'stĺpec','stĺpce','stĺpcov'):result.columns+' '+pluralWord(result.columns,'stĺpec','stĺpce','stĺpcov')} · zostava ${fmt(result.width)} × ${fmt(result.height)} cm`:'Pridaj svoj prvý rám';
$('coordinates').innerHTML=result.valid?result.items.flatMap((f,i)=>f.holes.map((h,j)=>`<tr><td><span class="number">${i+1}${f.holes.length>1?String.fromCharCode(65+j):''}</span>${esc(f.name)}</td><td>${fmt(h.x)} cm</td><td><strong>${fmt(h.y)} cm</strong></td><td>${fmt(f.top)} cm</td></tr>`)).join(''):'';
const pad=30;let svg=`<svg role="img" aria-label="Rozloženie rámov na stene širokej ${cfg.wallW} cm a vysokej ${cfg.wallH} cm" viewBox="${-pad} ${-pad} ${cfg.wallW+pad*2} ${cfg.wallH+pad*2}"><defs><pattern id="grid" width="${gridStep()}" height="${gridStep()}" patternUnits="userSpaceOnUse"><path d="M${gridStep()} 0H0V${gridStep()}" fill="none" stroke="#a4b79a" stroke-width=".35"/></pattern><filter id="shadow"><feDropShadow dx="1" dy="2" stdDeviation="1.5" flood-opacity=".15"/></filter></defs><rect width="${cfg.wallW}" height="${cfg.wallH}" fill="#f5f5ee"/><rect width="${cfg.wallW}" height="${cfg.wallH}" fill="${$('showGrid').checked?'url(#grid)':'none'}"/><path d="M0 -8H${cfg.wallW} M0 -11v6 M${cfg.wallW} -11v6" stroke="#899780" stroke-width=".5"/><text x="${cfg.wallW/2}" y="-13" text-anchor="middle" font-size="5" fill="#65745e">${fmt(cfg.wallW)} cm</text><text x="-14" y="${cfg.wallH/2}" text-anchor="middle" transform="rotate(-90 -14 ${cfg.wallH/2})" font-size="5" fill="#65745e">${fmt(cfg.wallH)} cm</text><line x1="0" y1="${cfg.wallH-cfg.center}" x2="${cfg.wallW}" y2="${cfg.wallH-cfg.center}" stroke="#aab9a1" stroke-width=".5" stroke-dasharray="2 2"/>`;
for(let [i,f] of result.items.entries()){svg+=`<g class="${f.id===selectedId?'selected-frame':''}" data-frame="${f.id}" tabindex="0" role="button" aria-label="Upraviť ${esc(f.name)}"><rect x="${f.x}" y="${f.y}" width="${f.w}" height="${f.h}" fill="${mode==='art'?'#fbfaf5':'#eef1e8'}" stroke="${mode==='art'?'#726b5c':'#98a88e'}" stroke-width="${mode==='art'?1.8:.6}" ${mode==='art'?'filter="url(#shadow)"':'stroke-dasharray="2 1"'}/>`;if(mode==='art'&&f.art){svg+=`<svg x="${f.x+f.w*.13}" y="${f.y+f.h*.13}" width="${f.w*.74}" height="${f.h*.74}" overflow="hidden"><image href="${esc(f.art)}" width="100%" height="100%" preserveAspectRatio="xMidYMid ${f.artFit==='contain'?'meet':'slice'}"/></svg><text x="${f.x+f.w/2}" y="${f.y+f.h*.96}" text-anchor="middle" fill="#516049" font-size="3.5">${i+1}</text>`;}else if(mode==='art')svg+=`<rect x="${f.x+f.w*.13}" y="${f.y+f.h*.13}" width="${f.w*.74}" height="${f.h*.74}" fill="${colors[i%colors.length]}"/><text x="${f.x+f.w/2}" y="${f.y+f.h/2-1}" text-anchor="middle" fill="#fff" font-size="${Math.min(f.w*.21,11)}" font-family="Georgia">${String(i+1).padStart(2,'0')}</text><text x="${f.x+f.w/2}" y="${f.y+f.h/2+7}" text-anchor="middle" fill="#fff" font-size="${Math.min(f.w*.09,4)}">${fmt(f.w)} × ${fmt(f.h)}</text>`;for(let [j,h] of f.holes.entries()){let y=cfg.wallH-h.y;svg+=`<circle cx="${h.x}" cy="${y}" r="1.7" fill="${mode==='art'?'#fff':'#315e4b'}" stroke="#315e4b" stroke-width=".5"/>`;if(mode==='drill')svg+=`<path d="M${h.x-3} ${y}h6 M${h.x} ${y-3}v6" stroke="#315e4b" stroke-width=".5"/><text x="${h.x}" y="${y+7}" font-size="4" fill="#315e4b" text-anchor="middle">${i+1}${f.holes.length>1?String.fromCharCode(65+j):''}</text>`}svg+='</g>'}
if(dragging&&alignGuides){let dr=result.items.find(it=>it.id===dragging.id);if(dr){const m=15,line=(x1,y1,x2,y2)=>`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="#d6564f" stroke-width=".5" stroke-dasharray="2 1.5" opacity=".85" pointer-events="none"/>`;
if(alignGuides.v){let o=result.items.find(it=>it.id===alignGuides.v.id);if(o)svg+=line(alignGuides.v.val,Math.min(dr.y,o.y)-m,alignGuides.v.val,Math.max(dr.y+dr.h,o.y+o.h)+m);}
if(alignGuides.h){let o=result.items.find(it=>it.id===alignGuides.h.id);if(o)svg+=line(Math.min(dr.x,o.x)-m,alignGuides.h.val,Math.max(dr.x+dr.w,o.x+o.w)+m,alignGuides.h.val);}
}}
svg+=`<line x1="0" y1="${cfg.wallH}" x2="${cfg.wallW}" y2="${cfg.wallH}" stroke="#819173" stroke-width="1"/><circle cx="0" cy="${cfg.wallH}" r="1.5" fill="#315e4b"/><text x="0" y="${cfg.wallH+10}" font-size="4" fill="#66745e">0 · ĽAVÝ OKRAJ / PODLAHA</text></svg>`;$('canvas').innerHTML=svg; syncSelection();renderDrillPlan();if(!dragging)saveLocal();}
function hookFields(hooks){$('hookInputs').innerHTML=hooks.map((h,i)=>`<p class="hook-title">Závesný bod ${hooks.length>1?String.fromCharCode(65+i):''}</p><div class="fields"><label>Od ľavého okraja<input class="hx" type="number" min="0" step="0.1" required value="${h.x}"></label><label>Od horného okraja<input class="hy" type="number" min="0" step="0.1" required value="${h.y}"></label></div>`).join('')}
function openEditor(id){editing=id;let f=frames.find(f=>f.id===id)||{name:'Rám '+nextId,w:30,h:40,hooks:[{x:15,y:5}]};artRequest++;draftArt=f.art||null;$('artFile').value='';$('artFit').value=f.artFit||'cover';$('artWhiteBg').checked=!!draftArt&&draftArt.startsWith('data:image/jpeg');$('artStatus').textContent='';$('saveFrame').disabled=false;refreshArtPreview();$('frameName').value=f.name;$('fw').value=f.w;$('fh').value=f.h;$('preset').value='custom';$('hookCount').value=f.hooks.length;hookFields(f.hooks);$('formError').textContent='';$('delete').hidden=id===null;$('editorTitle').textContent=id===null?'Pridať rám':'Upraviť rám';$('editor').showModal()}
function resetHooks(){let w=Number($('fw').value);hookFields($('hookCount').value==='1'?[{x:w/2,y:5}]:[{x:w*.2,y:5},{x:w*.8,y:5}])}
$('add').onclick=()=>openEditor(null);$('frames').onclick=e=>{let b=e.target.closest('[data-edit]');if(b)openEditor(Number(b.dataset.edit))};$('close').onclick=()=>$('editor').close();$('hookCount').onchange=resetHooks;$('preset').onchange=()=>{if($('preset').value==='custom')return;let [w,h]=$('preset').value.split(',');$('fw').value=w;$('fh').value=h;resetHooks();$('formError').textContent='Rozmer sa zmenil, poloha uška sa nastavila na predvolenú hodnotu — zmeraj a uprav ju.'};$('rotate').onclick=()=>{let w=$('fw').value;$('fw').value=$('fh').value;$('fh').value=w;$('preset').value='custom';resetHooks();$('formError').textContent='Rám je otočený. Poloha uška sa nastavila na predvolenú hodnotu — zmeraj a uprav ju znova.'};for(let k of ['fw','fh'])$(k).oninput=()=>{$('preset').value='custom'};
$('frameForm').onsubmit=e=>{e.preventDefault();if($('saveFrame').disabled)return;let w=Number($('fw').value),h=Number($('fh').value),name=$('frameName').value.trim(),hooks=[...document.querySelectorAll('.hx')].map((el,i)=>({x:Number(el.value),y:Number(document.querySelectorAll('.hy')[i].value)}));if(!name){$('formError').textContent='Zadaj názov rámu.';return}
if(hooks.some(p=>p.x>w||p.y>h)){$('formError').textContent='Závesný bod musí ležať vnútri rozmerov rámu.';return}
if(hooks.length===2&&hooks[0].x===hooks[1].x&&hooks[0].y===hooks[1].y){$('formError').textContent='Závesné body musia byť na rozdielnych miestach.';return}checkpoint();let f={...frames.find(f=>f.id===editing),id:editing??nextId++,name,w,h,hooks,art:draftArt,artFit:$('artFit').value};if(editing===null){if($('layoutType').value==='manual'){f.px=(config().wallW-w)/2;f.py=config().wallH-config().center-h/2;}frames.push(f);}else frames=frames.map(old=>old.id===editing?f:old);$('editor').close();render()};$('delete').onclick=()=>{checkpoint();frames=frames.filter(f=>f.id!==editing);$('editor').close();render()};for(let k of ['wallW','wallH','gap','center','columns','align'])$(k).addEventListener('input',()=>{if(k==='center'&&$('layoutType').value==='manual'){centerGroup();}else render()});for(let [id,m] of [['artMode','art'],['drillMode','drill']])$(id).onclick=()=>{mode=m;for(let b of ['artMode','drillMode']){$(b).classList.toggle('active',b===id);$(b).setAttribute('aria-pressed',b===id)}render()};$('print').onclick=()=>window.print();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'get_drilling_plan',description:'Read the currently visible frame layout and drilling coordinates in centimetres from the left wall edge and floor.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||Object.keys(input).length)throw Error('No arguments accepted');if(!result?.valid)throw Error('Layout does not fit the wall');return {wall:config(),frames:result.items.map(f=>({name:f.name,width:f.w,height:f.h,holes:f.holes}))}}})).catch(()=>{})}catch{}}

function saveLocal(){try{localStorage.setItem('obrazovna-plan-v2',JSON.stringify({frames,nextId,cfg:config(),grid:String(gridStep()),showGrid:$('showGrid').checked,snapGrid:$('snapGrid').checked}));$('saveStatus').textContent='Uložené v tomto prehliadači · cm'}catch{$('saveStatus').textContent='Uloženie nie je dostupné'}}
function restoreLocal(){try{let d=JSON.parse(localStorage.getItem('obrazovna-plan-v2'));if(!d||!Array.isArray(d.frames)||d.frames.length>24)return; if(!d.frames.every(f=>Number.isFinite(f.id)&&Number.isFinite(f.w)&&f.w>0&&Number.isFinite(f.h)&&f.h>0&&Array.isArray(f.hooks)&&f.hooks.every(h=>Number.isFinite(h.x)&&Number.isFinite(h.y))))return;frames=d.frames;nextId=Math.max(0,...frames.map(f=>f.id))+1;for(let k of ['wallW','wallH','gap','center','columns','align','layoutType'])if(d.cfg?.[k]!==undefined)$(k).value=d.cfg[k];if(Number.isFinite(Number(d.grid))&&Number(d.grid)>0)$('gridStep').value=d.grid;$('showGrid').checked=d.showGrid!==false;$('snapGrid').checked=d.snapGrid!==false}catch{}}
function capture(){return {frames:JSON.parse(JSON.stringify(frames)),cfg:config()}}
function checkpoint(){undoStack.push(capture());if(undoStack.length>40)undoStack.shift();$('undoLayout').disabled=false}
function restore(s){frames=s.frames;for(let [k,v] of Object.entries(s.cfg))$(k).value=v;render()}
function freezePositions(){if(!result)return;frames=frames.map(f=>{let p=result.items.find(i=>i.id===f.id);return {...f,px:p.x,py:p.y}});$('layoutType').value='manual'}
function syncSelection(){let f=result?.items.find(f=>f.id===selectedId);$('selection').hidden=!f;if(f){$('selectedName').textContent=f.name;$('posX').value=Number(f.x.toFixed(1));$('posTop').value=Number(f.top.toFixed(1));}let manual=$('layoutType').value==='manual';$('columns').disabled=manual;$('align').disabled=$('layoutType').value!=='rows';$('gap').disabled=false;$('undoLayout').disabled=!undoStack.length;previousLayout=$('layoutType').value}
function centerGroup(){if(!result?.items.length)return;checkpoint();freezePositions();let c=config(),minX=Math.min(...frames.map(f=>f.px)),minY=Math.min(...frames.map(f=>f.py));let dx=(c.wallW-result.width)/2-minX,dy=c.wallH-c.center-result.height/2-minY;frames.forEach(f=>{f.px+=dx;f.py+=dy});render();$('moveStatus').textContent='Zostava je vycentrovaná. Vzájomné polohy rámov zostali zachované.'}
$('centerGroup').onclick=centerGroup;$('undoLayout').onclick=()=>{let s=undoStack.pop();if(s)restore(s);$('moveStatus').textContent='Posledná zmena rozloženia bola vrátená.'};
let previousLayout=$('layoutType').value;$('layoutType').onchange=()=>{let value=$('layoutType').value;undoStack.push({...capture(),cfg:{...config(),layoutType:previousLayout}});if(value==='manual')freezePositions();previousLayout=value;render()};
for(let k of ['showGrid','snapGrid'])$(k).onchange=render;
$('gridStep').oninput=()=>{const n=Number($('gridStep').value.trim().replace(',', '.')),valid=Number.isFinite(n)&&n>0;$('gridStep').setCustomValidity(valid?'':'Zadaj kladné číslo, napríklad 2,5.');$('gridStep').setAttribute('aria-invalid',String(!valid));if(valid)render()};
$('gridStep').onchange=()=>$('gridStep').reportValidity();
$('editSelected').onclick=()=>openEditor(selectedId);
function changePosition(id,x,y,snap=false){let f=frames.find(f=>f.id===id),c=config();let others=frames.filter(o=>o.id!==id).map(o=>({...o,x:o.px,y:o.py}));let align=snap?findAlignment({x,y,w:f.w,h:f.h},others):null;let tx=align?.guideX?align.x:x,ty=align?.guideY?align.y:y;if(snap&&$('snapGrid').checked){let step=gridStep();if(!align?.guideX)tx=Math.round(tx/step)*step;if(!align?.guideY)ty=Math.round(ty/step)*step;}let p=placeWithGap(f,others,tx,ty,c,snap);alignGuides=null;if(p){f.px=p.x;f.py=p.y;if(align){let v=align.guideX&&Math.abs(p.x-align.x)<0.01?align.guideX:null,h=align.guideY&&Math.abs(p.y-align.y)<0.01?align.guideY:null;if(v||h)alignGuides={v,h};}}else $('moveStatus').textContent='Na stene nie je voľné miesto s nastavenou medzerou.';}
for(let k of ['posX','posTop'])$(k).onchange=()=>{let x=Number($('posX').value),y=config().wallH-Number($('posTop').value);if(!Number.isFinite(x)||!Number.isFinite(y))return;checkpoint();freezePositions();changePosition(selectedId,x,y);render()};
function focusSelected(){if(selectedId)$('canvas').querySelector(`[data-frame="${selectedId}"]`)?.focus({preventScroll:true})}
let suppressClick=false,lastTap=null;
$('canvas').onclick=e=>{if($('editor').open)return;if(suppressClick){suppressClick=false;return}let g=e.target.closest('[data-frame]');selectedId=g?Number(g.dataset.frame):null;render();focusSelected()};
$('canvas').ondblclick=e=>{let g=e.target.closest('[data-frame]');if(g)openEditor(Number(g.dataset.frame))};
function wallPoint(e){let svg=$('canvas').querySelector('svg');return new DOMPoint(e.clientX,e.clientY).matrixTransform(svg.getScreenCTM().inverse())}
$('canvas').onpointerdown=e=>{if(e.button!==0||dragging)return;let g=e.target.closest('[data-frame]');if(!g||!result)return;let id=Number(g.dataset.frame),f=result.items.find(f=>f.id===id),p=wallPoint(e);selectedId=id;alignGuides=null;dragging={id,pointerId:e.pointerId,start:p,clientX:e.clientX,clientY:e.clientY,x:f.x,y:f.y,before:capture(),moved:false};$('canvas').setPointerCapture(e.pointerId);e.preventDefault()};
$('canvas').onpointermove=e=>{if(!dragging||e.pointerId!==dragging.pointerId)return;let d=dragging;if(!d.moved&&Math.hypot(e.clientX-d.clientX,e.clientY-d.clientY)<4)return;if(!d.moved){freezePositions();d.moved=true}let p=wallPoint(e);changePosition(d.id,d.x+p.x-d.start.x,d.y+p.y-d.start.y,true);render();$('moveStatus').textContent=result.overlap?'Rámy sa prekrývajú — po pustení sa rám vráti.':`${frames.find(f=>f.id===d.id).name} · minimálna medzera ${fmt(config().gap)} cm.`;};
function finishDrag(e,cancel=false){if(!dragging||e.pointerId!==dragging.pointerId)return;let d=dragging;dragging=null;alignGuides=null;if($('canvas').hasPointerCapture(e.pointerId))$('canvas').releasePointerCapture(e.pointerId);if(d.moved){suppressClick=true;if(cancel||!result.valid){restore(d.before);$('moveStatus').textContent='Poloha nebola voľná. Rám sa vrátil na pôvodné miesto.'}else{undoStack.push(d.before);render();$('moveStatus').textContent='Poloha uložená. Body vŕtania sú prepočítané.'}}else{let now=Date.now();if(lastTap?.id===d.id&&now-lastTap.time<450){lastTap=null;openEditor(d.id)}else{lastTap={id:d.id,time:now};render()}}if(!$('editor').open)focusSelected()}
$('canvas').onpointerup=e=>finishDrag(e);$('canvas').onpointercancel=e=>finishDrag(e,true);
$('canvas').onkeydown=e=>{let id=Number(e.target.closest('[data-frame]')?.dataset.frame);if(!id)return;if(e.key==='Enter'){openEditor(id);return}let dirs={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]};if(!dirs[e.key])return;e.preventDefault();selectedId=id;checkpoint();freezePositions();let f=frames.find(f=>f.id===id),v=dirs[e.key],step=e.shiftKey?10:1;changePosition(id,f.px+v[0]*step,f.py+v[1]*step);render();$('canvas').querySelector(`[data-frame="${id}"]`)?.focus()};
let isSample=!localStorage.getItem('obrazovna-plan-v2');restoreLocal();render();

function refreshArtPreview(){ $('artPreviewBox').hidden=!draftArt;if(draftArt){$('artPreview').src=draftArt;$('artPreview').style.objectFit=$('artFit').value;}else $('artPreview').removeAttribute('src'); }
$('artFit').onchange=refreshArtPreview;
$('rotateArt').onclick=async()=>{
 if(!draftArt)return;
 $('rotateArt').disabled=true;
 try{const type=(draftArt.match(/^data:([^;]+)/)||[])[1]||'image/png';const img=new Image();img.src=draftArt;await img.decode();
 const canvas=document.createElement('canvas');canvas.width=img.naturalHeight;canvas.height=img.naturalWidth;
 const ctx=canvas.getContext('2d');ctx.translate(canvas.width/2,canvas.height/2);ctx.rotate(Math.PI/2);ctx.drawImage(img,-img.naturalWidth/2,-img.naturalHeight/2);
 draftArt=type==='image/jpeg'?canvas.toDataURL(type,.78):canvas.toDataURL(type);
 refreshArtPreview();
 }finally{$('rotateArt').disabled=false;}
};
$('removeArt').onclick=()=>{artRequest++;draftArt=null;$('artFile').value='';$('artStatus').textContent='Obrázok sa odstráni po uložení rámu.';$('saveFrame').disabled=false;refreshArtPreview()};
$('editor').addEventListener('close',()=>{artRequest++});
$('artFile').onchange=async()=>{
 const file=$('artFile').files[0];if(!file)return;const request=++artRequest;$('saveFrame').disabled=false;
 if(!['image/jpeg','image/png','image/webp','image/avif'].includes(file.type)||file.size>20*1024*1024){$('artStatus').textContent='Vyber JPG, PNG, WebP alebo AVIF do 20 MB.';return;}
 $('saveFrame').disabled=true;$('artStatus').textContent='Pripravujem náhľad…';let url=URL.createObjectURL(file);
 try{const img=new Image();img.src=url;await img.decode();if(request!==artRequest)return;let ratio=Math.min(1,900/Math.max(img.naturalWidth,img.naturalHeight)),canvas=document.createElement('canvas'),data;
 const fillWhite=$('artWhiteBg').checked||file.type==='image/jpeg';
 for(let attempt=0;attempt<8;attempt++){canvas.width=Math.max(1,Math.round(img.naturalWidth*ratio));canvas.height=Math.max(1,Math.round(img.naturalHeight*ratio));const ctx=canvas.getContext('2d');if(fillWhite){ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);}ctx.drawImage(img,0,0,canvas.width,canvas.height);data=fillWhite?canvas.toDataURL('image/jpeg',.78):canvas.toDataURL('image/png');if(data.length<=90000)break;ratio*=.75;}
 if(data.length>90000)throw Error('size');if(request!==artRequest)return;draftArt=data;refreshArtPreview();$('artStatus').textContent='Obrázok je pripravený. Potvrď tlačidlom Uložiť rám.';
 }catch{if(request===artRequest)$('artStatus').textContent='Obrázok sa nepodarilo načítať. Skús JPG alebo PNG.';}finally{URL.revokeObjectURL(url);if(request===artRequest)$('saveFrame').disabled=false;}
};
