// Every offset uses the same reference hole, avoiding accumulated measuring errors.
function drillingPoints(items){return items.flatMap((f,i)=>f.holes.map((h,j)=>({...h,key:f.id+':'+j,label:String(i+1)+(f.holes.length>1?String.fromCharCode(65+j):''),name:f.name,frameId:f.id})));}
function drillingOffsets(points,reference){return points.map(p=>({...p,dx:p.x-reference.x,dy:p.y-reference.y}));}
if(typeof module!=='undefined')module.exports={drillingPoints,drillingOffsets};
let drillReference=null,drillTarget='all';
function renderDrillPlan(){
 const root=document.getElementById('drillPlan');if(!root)return;
 if(!result?.valid||!result.items.length){root.innerHTML='<p class="hint">Kótovaná mapa sa zobrazí, keď sa rámy zmestia na stenu bez prekrývania.</p>';return;}
 const points=drillingPoints(result.items);let ref=points.find(p=>p.key===drillReference)||points[0];drillReference=ref.key;
 let offsets=drillingOffsets(points,ref),others=offsets.filter(p=>p.key!==ref.key),target=others.find(p=>p.key===drillTarget);if(drillTarget!=='all'&&!target)drillTarget='all';const targets=drillTarget==='all'?others:target?[target]:[];
 const text=(n)=>fmt(Math.abs(n)),horizontal=n=>Math.abs(n)<0.00001?'rovnaká zvislica':`${text(n)} cm ${n<0?'doľava':'doprava'}`,vertical=n=>Math.abs(n)<0.00001?'rovnaká výška':`${text(n)} cm ${n<0?'nadol':'nahor'}`;
 root.innerHTML=`<div class="drill-controls"><label>Prvá diera<select id="drillReference">${points.map(p=>`<option value="${p.key}" ${p.key===ref.key?'selected':''}>${p.label} · ${esc(p.name)}</option>`).join('')}</select></label>${others.length?`<label>Kóty na mape<select id="drillTarget"><option value="all" ${drillTarget==='all'?'selected':''}>Všetky diery naraz</option>${others.map(p=>`<option value="${p.key}" ${p.key===drillTarget?'selected':''}>${p.label} · ${esc(p.name)}</option>`).join('')}</select></label>`:''}<button class="primary" id="printDrill">Vytlačiť kótovanú mapu</button></div><div class="first-hole"><span class="number">${ref.label}</span><div><strong>Začni touto dierou</strong><p>${fmt(ref.x)} cm od ľavého okraja steny · ${fmt(ref.y)} cm nad podlahou.</p></div></div><div id="drillMap"></div>${others.length?`<p class="drill-instruction">Cez prvú značku ${ref.label} si vodováhou vyznač vodorovnú čiaru. Po nej odmeraj posun doľava alebo doprava, potom z tohto miesta zvislo nahor alebo nadol. Všetky kóty sú od prvej diery ${ref.label}, nie od predchádzajúcej.</p>`:''}<h3 class="procedure-title">Postup krok za krokom</h3><div class="first-step"><strong>1. Zameraj prvú dieru ${ref.label}</strong><p>Od ľavého okraja steny odmeraj ${fmt(ref.x)} cm a od podlahy ${fmt(ref.y)} cm. Označ bod ceruzkou a vodováhou cez neho vyznač vodorovnú čiaru.</p></div><div class="drill-cards">${others.map((p,i)=>`<article class="drill-card"><h3><span class="step-number">${i+2}.</span> Označ dieru ${p.label} · ${esc(p.name)}</h3><p class="step-origin">Meraj od prvej diery ${ref.label}</p>${stepDiagram(p,ref)}<p><strong>${horizontal(p.dx)}</strong> · <strong>${vertical(p.dy)}</strong></p><small>Kontrola: ${fmt(p.x)} cm zľava, ${fmt(p.y)} cm od podlahy.</small></article>`).join('')}</div><p class="finish-step"><strong>${points.length+1}. Skontroluj značky a vyvŕtaj ${points.length===1?'dieru':'diery'}</strong></p><p class="hint">Najprv označ všetky body ceruzkou a skontroluj ich vodováhou. Až potom vŕtaj. Kóty sú v cm, zaokrúhlené na 1 mm; kresba nie je šablóna v mierke 1 : 1.</p>`;
 const minX=Math.min(...result.items.map(f=>f.x)),maxX=Math.max(...result.items.map(f=>f.x+f.w)),minY=Math.min(...result.items.map(f=>config().wallH-f.y-f.h)),maxY=Math.max(...result.items.map(f=>config().wallH-f.y));
 const scale=Math.min(600/Math.max(maxX-minX,1),300/Math.max(maxY-minY,1)),ox=400-(maxX-minX)*scale/2,oy=70;
 const X=x=>ox+(x-minX)*scale,Y=y=>oy+(maxY-y)*scale;
 const W=800+Math.max(0,targets.length-1)*55,H=460+Math.max(0,targets.length-1)*34;
 let svg=`<svg viewBox="0 0 ${W} ${H}" style="min-width:0" role="img" aria-label="Kótovaná mapa dier. Referenčný bod ${ref.label}. ${targets.map(p=>`Bod ${p.label}: ${horizontal(p.dx)}, ${vertical(p.dy)}`).join('; ')}"><defs><marker id="dimensionArrow" viewBox="0 0 10 10" refX="5" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M10 5L0 0V10Z" fill="#315e4b"/></marker></defs><rect width="${W}" height="${H}" fill="#fafcf7"/>`;
 for(let f of result.items)svg+=`<rect x="${X(f.x)}" y="${Y(config().wallH-f.y)}" width="${f.w*scale}" height="${f.h*scale}" fill="#eaf0e6" fill-opacity=".45" stroke="#c1cdb9" stroke-dasharray="5 4"/>`;
 svg+=`<path d="M35 ${Y(ref.y)}H${W-25} M${X(ref.x)} 25V${H-40}" stroke="#91ab82" stroke-dasharray="5 5"/><text x="35" y="${Math.max(20,Y(ref.y)-10)}" fill="#55704b" font-size="13">Vodorovná čiara cez ${ref.label}</text>`;
 for(let [i,p] of targets.entries()){let a=X(ref.x),b=X(p.x),c=Y(ref.y),d=Y(p.y),laneY=390+i*34,laneX=745+i*55;
  if(targets.length===1)svg+=`<path d="M${a} ${c}H${b}V${d}" fill="none" stroke="#315e4b" stroke-width="2"/>`;
  svg+=`<path d="M${a} ${c}V${laneY+5} M${b} ${d}V${laneY+5}" stroke="#bac7b1" stroke-width=".7"/><path d="M${a} ${laneY}H${b}" stroke="#315e4b" ${Math.abs(p.dx)>.00001?'marker-start="url(#dimensionArrow)" marker-end="url(#dimensionArrow)"':''}/>${dimensionText(Math.abs(p.dx)>.00001?(a+b)/2:a+65,laneY+19,`${ref.label} → ${p.label}: ${text(p.dx)} cm`)}
  <path d="M${a} ${c}H${laneX+5} M${b} ${d}H${laneX+5}" stroke="#bac7b1" stroke-width=".7"/><path d="M${laneX} ${c}V${d}" stroke="#315e4b" ${Math.abs(p.dy)>.00001?'marker-start="url(#dimensionArrow)" marker-end="url(#dimensionArrow)"':''}/><g transform="translate(${laneX+18} ${(c+d)/2}) rotate(-90)">${dimensionText(0,0,`${ref.label} → ${p.label}: ${text(p.dy)} cm`)}</g>`;
 }
 for(let p of points){svg+=`<circle cx="${X(p.x)}" cy="${Y(p.y)}" r="${p.key===ref.key?8:5}" fill="#315e4b" stroke="white" stroke-width="2"/><path d="M${X(p.x)-10} ${Y(p.y)}h20 M${X(p.x)} ${Y(p.y)-10}v20" stroke="#315e4b"/>${dimensionText(X(p.x)+16,Y(p.y)-13,p.label)}`;}
 svg+=`<text x="${W/2}" y="${H-12}" text-anchor="middle" font-size="14" fill="#55704b">${targets.length>1?'Všetky kóty od diery '+ref.label+' · dole vodorovné, vpravo zvislé vzdialenosti':target?`${ref.label} → ${target.label} : ${horizontal(target.dx)} · ${vertical(target.dy)}`:'Zameraj prvú dieru podľa hodnôt nad mapou.'}</text></svg>`;
 $('drillMap').innerHTML=svg;
 $('drillReference').onchange=e=>{drillReference=e.target.value;renderDrillPlan()};if(others.length)$('drillTarget').onchange=e=>{drillTarget=e.target.value;renderDrillPlan()};$('printDrill').onclick=()=>window.print();
}
function dimensionText(x,y,label){return `<text x="${x}" y="${y}" text-anchor="middle" font-size="15" font-weight="600" fill="#264932" stroke="#fafcf7" stroke-width="5" paint-order="stroke">${label}</text>`}
function stepDiagram(p,ref){
 const dx=Math.abs(p.dx)<.00001?0:p.dx,dy=Math.abs(p.dy)<.00001?0:p.dy;
 let ax=dx<0?235:65,bx=dx===0?ax:dx<0?65:235,ay=dy>0?115:45,by=dy===0?ay:dy>0?45:115;
 return `<svg class="step-diagram" viewBox="0 0 300 165" role="img" aria-label="Posun od diery ${ref.label} k diere ${p.label}"><path d="M${ax} ${ay}H${bx}V${by}" stroke="#315e4b" stroke-width="2" fill="none"/><circle cx="${ax}" cy="${ay}" r="5" fill="white" stroke="#315e4b" stroke-width="2"/><circle cx="${bx}" cy="${by}" r="5" fill="#315e4b"/><text x="${ax-15}" y="${ay+5}" text-anchor="end" font-size="14" fill="#315e4b">${ref.label}</text><text x="${bx+14}" y="${by+5}" font-size="14" fill="#315e4b">${p.label}</text>${dx?dimensionText((ax+bx)/2,ay+(dy>0?24:-15),fmt(Math.abs(dx))+' cm'):''}${dy?dimensionText(bx+(dx<0?42:-42),(ay+by)/2+5,fmt(Math.abs(dy))+' cm'):''}</svg>`;
}
